title:
  Yawar Raza
description:
  [Profile](https://YawarRaza7349.github.io), [Projects](https://YawarRaza7349.github.io/projects), [Portfolio](https://YawarRaza7349.github.io/creative)
include:
  - index.md
  - projects.md
  - creative.md
theme:
  jekyll-theme-midnight
